name: '[Reusable] Publish new release'

on:
  workflow_call:
    inputs:
      filename:
        type: string

jobs:
  reusable_workflow_job:
    runs-on:  ubuntu-latest
    steps:
    - name: "Download build"
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.filename }}

    - uses: vimtor/action-zip@v1.2
      with:
        files: H.Core/
        dest: ${{ inputs.filename }}.zip

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: $SHORT_SHA
        release_name: Holos 4 - $SHORT_SHA
        draft: true
        prerelease: false

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ inputs.filename }}.zip
        asset_name: ${{ inputs.filename }}.zip
        asset_content_type: application/zip

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
