name: '[Reusable] Build'

on:
  workflow_call:
    inputs:
      configuration:
        type: string
      filename:
        type: string

jobs:
  reusable_workflow_job:
    runs-on:  windows-latest    
    steps:
    
    - name: Get date/time
      id: t1
      uses: Kaven-Universe/github-action-current-date-time@v1.4.0
      with:
        format: "YYYYMMDD.HHmm"

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # - name: Setup VSTest
    #   uses: darenm/Setup-VSTest@v1

    - name: Restore nuget packages
      run: msbuild H.Core/H.Core.csproj /t:Restore /m
      env:
        Configuration: ${{ inputs.configuration }}

    - name: Build solution
      run: msbuild H.Core/H.Core.csproj /t:pack /p:Version=4.0.${{ steps.t1.outputs.time }} /p:Configuration=${{ inputs.configuration }} /m
      env:
        Configuration: ${{ inputs.configuration }}
        
    # TODO: remove unit tests for now, to speed up testing
    # - name: Run Tests
    #   run: vstest.console.exe ./**/H.Core.Test/bin/${{ inputs.configuration }}/H.Core.Test.dll ./**/H.Infrastructure.Test/bin/${{ inputs.configuration }}/H.Infrastructure.Test.dll ./**/H.CLI.Test/bin/${{ inputs.configuration }}/H.CLI.Test.dll /Parallel

    - name: Upload build artifacts
      if: ${{ inputs.configuration == 'Release' }}
      uses: actions/upload-artifact@v4
      with:
        name: Holos4-lib
        path: '**/H.Core/bin/*'