name: '[Reusable] Pack and publish nuget package'

on:
  workflow_call:
    inputs:
      filename:
        type: string

jobs:
  reusable_workflow_job:
    runs-on:  ubuntu-latest
    steps:

    - name: "Download build"
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.filename }}

    - name: Add registry
      run: dotnet nuget add source --username f-aa --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/f-aa/index.json"

    - name: Publish package
      run: dotnet nuget push "bin/Release/aafc.holos.4.*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Holos4-nuget-pkg
        path: '**/H.Core/bin/Release/aafc.holos.4.*.nupkg'