name: Build and publish new release

on:
  push:
    branches: [ "nuget-package" ] # TODO: for testing, set back to main!

jobs:
  build:
    uses: ./.github/workflows/_dotnet-build-template.yml
    with:
      configuration: Release
      solution: Holos.sln
      filename: Holos4-lib

  nuget:
    uses: ./.github/workflows/_dotnet-nuget-template.yml
    with:
      filename: Holos4-lib
      
  publish:
    needs: build
    uses: ./.github/workflows/_dotnet-publish-template.yml
    with:
      filename: Holos4-lib

