name: Build and Test

on:
  push:
    branches: [ "pr-test" ]

jobs:
  build:
    uses: ./.github/workflows/_dotnet-build-template.yml
    with:
      configuration: Release
      solution: Holos.sln
      filename: Holos4-lib

  publish:
    needs: build
    uses: ./.github/workflows/_dotnet-publish-template.yml
    with:
      filename: Holos4-lib
